### ISSUE TITLE
MCConfigurator dictionary does not compile with yaml-cpp 0.5.2-4ubuntu1

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#1073]
OS: Ubuntu `18.04`
`libyaml-cpp-dev`: `0.5.2-4ubuntu1`
FairRoot: `v18.6.3`

```
In file included from input_line_11:114:
In file included from /usr/include/yaml-cpp/yaml.h:17:
In file included from /usr/include/yaml-cpp/node/impl.h:11:
In file included from /usr/include/yaml-cpp/node/iterator.h:13:
/usr/include/yaml-cpp/node/detail/iterator.h:48:54: error: no member named 'next' in namespace 'boost'
  void increment() { this->base_reference() = boost::next(this->base()); }
                                              ~~~~~~~^
Error: /root/FairSoft/install/bin/rootcint: compilation failure (/root/build/fairtools/MCConfigurator/G__MCConfigurator91733af92b_dictUmbrella.h)
fairtools/MCConfigurator/CMakeFiles/MCConfigurator.dir/build.make:81: recipe for target 'fairtools/MCConfigurator/G__MCConfigurator.cxx' failed
make[2]: *** [fairtools/MCConfigurator/G__MCConfigurator.cxx] Error 1
CMakeFiles/Makefile2:2152: recipe for target 'fairtools/MCConfigurator/CMakeFiles/MCConfigurator.dir/all' failed
make[1]: *** [fairtools/MCConfigurator/CMakeFiles/MCConfigurator.dir/all] Error 2
```

A workaround is passing `-DCMAKE_DISABLE_FIND_PACKAGE_yaml-cpp=ON` to the FairRoot CMake configure command.
