### ISSUE TITLE
Tutorial4 does not build with ROOT 6.14/04

### ISSUE THREAD

**Issue by olantwin** [FairRootGroup/FairRoot#822]
**Describe the bug**

The build fails, as `TGeoMatrix` does not have a suitable `operator*` anymore.

```
/home/ol11/Projects/ship_software/sw/SOURCES/FairRoot/dev/0/examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx: In member function 'void FairTutorialDet4::ModifyGeometryByFullPath()':
/home/ol11/Projects/ship_software/sw/SOURCES/FairRoot/dev/0/examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx:364:30: error: no match for 'operator*' (operand types are 'TGeoMatrix' and 'TGeoCombiTrans')
     TGeoHMatrix nlocal = *l3 * localdelta;
                          ~~~~^~~~~~~~~~~~
```

**To Reproduce**

Build using `aliBuild`.

**Expected behavior**
Build without issues.

**Logs / Screenshots**

[Full log](https://gist.github.com/olantwin/cad62b46e14f3d8b1cf6da430e2eed4) (note: incremental build with `aliBuild`, but also happens with clean build without `FairRoot` as a development package).

**System information (please complete the following information):**
 - OS:  Fedora 28
 - Compiler: GCC 8.1.1
 - Environment: `aliBuild` using a personal version of `shipdist`; `fairroot.sh` the same as `alfadist` as of commit 5c31cc7fe5f59da12fd91b0b9497054871297ea8, `root.sh` unmodified from `shipdist`.

**Additional context**

----------

Please let me know if you need any additional information!

**Comment by ihrivnac** [comment]
By a coincidence, there is just proposed a fix in PR #827.
Even with this fix, I get a problem to view the produced ROOT files in Tutorial4 and rutherford.
When I look in the generated file with Root browser and try to click
for eg. TutorialDetPoint.fPy, this works fine for Tutorial1 and Tutorial2, but hangs for Tutorial4 and rutherford; it does not matter whether you simulate with G3 or G4.

And when I try to read the file with the following commands it ends with segmentation fault:
TFile f("testrun_TGeant3.root");
TTree* t1 = (TTree*)f.Get("cbmsim");
TClonesArray *TutorialDetPoints  = new TClonesArray("FairTutorialDet4Point");
t1->SetBranchAddress("TutorialDetPoint",      &TutorialDetPoints);
t1->GetEntry(0)

Segmentation fault: 11
The same commands work ok with Tutorial2.

**Comment by olantwin** [comment]
Thanks! I can confirm that this fixes the build issue for me.

I have no idea why you get that behaviour when trying to read the resulting files, it probably warrants a separate issue.

**Comment by ihrivnac** [comment]
You have to run the tutorial macros first. I do it in this way:
cd mypath/sw/osx_x86-64/FairRoot/latest/share/fairbase/examples/simulation/Tutorial4
mkdir data # this step is needed only for some tutorials
root -b -q run_tutorial4.C
This will produce the testrun_TGeant3.root file, which you can try to process with the commands above.

**Comment by olantwin** [comment]
I can the mentioned issues, e.g. accessing the TutorialDetPoint.fPy 
branch hangs and in fact managed to completely freeze my machine.

**Comment by dennisklein** [comment]
Some more info for narrowing down the issue: Just tried Ivana's commands on Tutorial4 with FairRoot `dev` and FairSoft `may18` (ROOT 6.12/06) on Fedora 28 and they seem to work - no segfault.

**Comment by ihrivnac** [comment]
I tried on Mac High Sierra 10.13.4 with FairRoot build via alibuild (recipe defaults-o2 plus FairRoot tests enabled). Do you have a possibility to test on MAC?

**Comment by olantwin** [comment]
Since I can reproduce the issues here on Fedora, I don't think this can be (exclusively a macOS issue).

@ihrivnac: Do you see these issues only with your patchset?

**Comment by ihrivnac** [comment]
No, I get the problem also with "rutheford" example when testing only with the modifications in FairTutorialDet4.cxx (needed to get FairRoot compiled). So the problem cannot come frm the patch proposed.

**Comment by MohammadAlTurany** [comment]
I created a new issue with the exact (issue #828) problem as the compiling one is solved by PR #827 from Ivana.
